using System.Collections.Generic;
using System;
using YamlDotNet.Core.Tokens;

namespace ReadRedoLogContents
{
    internal class Record
    {
        public const string SEPARATOR = "#";

        private string? _opr;

        // Namepace and class name
        private string? _type;
        private List<object>? _fixedProps;
        private Dictionary<string, object>? _dynamicProps;

        // uid is an id used internally by GigaSpaces and for display purposes
        // if autoGenerate == true
        //   uid is the autoGenerated id
        // else
        //   Fields are separated with ^ (caret)
        //   First field is the hashCode of the classname including package name
        //   Second field is the length of the classname including package
        //   Third field is toString of getId()
        //   Last field is always ^0^0.
        // See: github.com/xap/xap SpaceUidFactory.java
        private string? _uid;
        private string? _changes;

        public Record() { }
        public Record(String opr, String type, List<Object> fixedProps, Dictionary<String, Object> dynamicProps, String uid, String changes)
        {
            this.Opr = opr;
            this.Type = type;
            this.FixedProps = fixedProps;
            this.DynamicProps = dynamicProps;
            this.Uid = uid;
            this.Changes = changes;

        }

        public String Opr { get { return _opr; } set { _opr = value; } }
        public String Type { get { return _type; } set { _type = value; } }
        public List<Object> FixedProps { get { return _fixedProps; } set { _fixedProps = value; } }
        public Dictionary<String, Object> DynamicProps { get { return _dynamicProps; } set { _dynamicProps = value; } }
        public String Uid { get { return _uid; }  set { _uid = value; } }
        public String Changes { get { return _changes; } set { _changes = value; } }

        public override string ToString()
        {
            return base.ToString() + ": " +
                this.Opr + Record.SEPARATOR + 
                this.Type + Record.SEPARATOR +
                this.Uid;
        }

    }
}